server:
  port: 8080

spring:
  application:
    name: booking
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/booking
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true